# USE THIS FILE WITH "REST CLIENT" VSCODE EXTENSION

### Get posts authorizeds
GET http://localhost:3000/posts
# Authorization: Bearer JWT using Login method
#Request Headers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTG9yZW4iLCJpYXQiOjE2MzQwNzgxNzgsImV4cCI6MTYzNDA3ODE5OH0.Kix-e2dwVsgHZ0muZYE06N7ew4aeMGMqK7kWFwj3epw

### refresh Token
POST http://localhost:4000/token
# token: refreshToken JWT using Login method
#Request Headers
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTG9yZW4iLCJpYXQiOjE2MzQwNzY5MzAsImV4cCI6MTYzNDA3Njk3MH0.7pW7o9ARfBu0Gp7m3eQmynJesxtt4fCzobfBOuO-qME"
}

### Login 
POST http://localhost:4000/login
#Request Headers
Content-Type: application/json

{
    "username": "Loren"
}

### Delete token
DELETE http://localhost:4000/logout
# token: refreshToken JWT using Login method
#Request Headers
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTG9yZW4iLCJpYXQiOjE2MzQwNzY4MjUsImV4cCI6MTYzNDA3Njk0NX0.0LnwHv0PaU9lA8fQtul2DG1W0k-HaRnQXRitZit9Dgk"
}